/**
 * AlertsScreen.js
 * Author: jayis1
 * Copyright (c) 2026 jayis1
 */
import React from 'react';
import { ScrollView, View, Text, StyleSheet } from 'react-native';
import { alertFlagsToList, sampleTelemetry } from '../utils/protocol';

const recommendations = [
  'Clean the exterior wall cap and verify the flap opens freely.',
  'Inspect the flexible hose behind the dryer for crushing or kinks.',
  'If using a gas dryer, check the room for positive air supply and confirm CO alarms are installed.',
  'Run the post-service comparison workflow to store a fresh baseline.'
];

export default function AlertsScreen() {
  const alerts = alertFlagsToList(sampleTelemetry.alerts);

  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      <Text style={styles.title}>Alert Center</Text>
      <Text style={styles.subtitle}>Action-oriented diagnostics generated by DryerFlow Guardian • Author: jayis1</Text>
      {alerts.map((alert) => (
        <View key={alert} style={styles.alertCard}>
          <Text style={styles.alertText}>{alert}</Text>
        </View>
      ))}
      <View style={styles.card}>
        <Text style={styles.sectionTitle}>Recommended next steps</Text>
        {recommendations.map((item) => <Text key={item} style={styles.item}>• {item}</Text>)}
      </View>
      <View style={styles.card}>
        <Text style={styles.sectionTitle}>Escalation policy</Text>
        <Text style={styles.paragraph}>When backdraft score exceeds 45 or CO rises above the configured threshold during an active run, the app promotes the event to high priority and suppresses routine advisory batching.</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020617' },
  content: { padding: 16, paddingBottom: 30 },
  title: { color: '#f8fafc', fontSize: 24, fontWeight: '700' },
  subtitle: { color: '#94a3b8', marginTop: 6, marginBottom: 16 },
  alertCard: { backgroundColor: '#7f1d1d', borderRadius: 14, padding: 14, marginBottom: 10 },
  alertText: { color: '#fee2e2', fontWeight: '600' },
  card: { backgroundColor: '#111827', borderRadius: 16, padding: 16, marginTop: 12 },
  sectionTitle: { color: '#f8fafc', fontWeight: '700', marginBottom: 8 },
  item: { color: '#d1d5db', marginBottom: 6, lineHeight: 20 },
  paragraph: { color: '#cbd5e1', lineHeight: 20 }
});
