/**
 * ServiceScreen.js
 * Author: jayis1
 * Copyright (c) 2026 jayis1
 */
import React from 'react';
import { ScrollView, View, Text, StyleSheet } from 'react-native';

const checklist = [
  ['Before cleaning', 'Capture current VRI, service horizon, and dry-down time.'],
  ['Vent path', 'Brush and vacuum the full duct, elbows, wall box, and exterior hood.'],
  ['Dryer rear hose', 'Replace thin foil hose with rigid or semi-rigid metal where permitted.'],
  ['After cleaning', 'Run the validation cycle and compare airflow and pressure against baseline.'],
  ['Refresh baseline', 'Store a new post-service baseline only if the vent path layout changed.']
];

export default function ServiceScreen() {
  return (
    <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
      <Text style={styles.title}>Service Coach</Text>
      <Text style={styles.subtitle}>Maintenance workflow generated by DryerFlow Guardian • Author: jayis1</Text>
      {checklist.map(([title, body]) => (
        <View key={title} style={styles.card}>
          <Text style={styles.cardTitle}>{title}</Text>
          <Text style={styles.cardBody}>{body}</Text>
        </View>
      ))}
      <View style={styles.summary}>
        <Text style={styles.summaryTitle}>Value for property teams</Text>
        <Text style={styles.summaryBody}>The before/after comparison screen gives maintenance staff a measurable record that service actually restored flow, reduced vent resistance, and improved drying efficiency.</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#020617' },
  content: { padding: 16, paddingBottom: 30 },
  title: { color: '#f8fafc', fontSize: 24, fontWeight: '700' },
  subtitle: { color: '#94a3b8', marginTop: 6, marginBottom: 16 },
  card: { backgroundColor: '#111827', borderRadius: 16, padding: 16, marginBottom: 12 },
  cardTitle: { color: '#f8fafc', fontWeight: '700', marginBottom: 6 },
  cardBody: { color: '#cbd5e1', lineHeight: 20 },
  summary: { backgroundColor: '#0f172a', borderRadius: 16, padding: 16, marginTop: 6 },
  summaryTitle: { color: '#f8fafc', fontWeight: '700', marginBottom: 8 },
  summaryBody: { color: '#cbd5e1', lineHeight: 20 }
});
