/**
 * ReportGenerator.js — SonicSight Companion
 * Generates PDF diagnostic reports from scan data, including tomogram
 * image, anomaly detection results, and compliance statements.
 * @author jayis1
 */

/**
 * Generate a PDF report string (simplified Markdown → PDF pipeline stub).
 * In production, this would use a library like react-native-html-to-pdf
 * or react-native-pdf-lib.
 *
 * @param {object} scanData - Full scan record
 * @param {Float32Array} tomogram - Reconstructed velocity image
 * @param {number} gridSize - Image grid dimension
 * @returns {string} Report content as Markdown/HTML
 */
export function generateReport(scanData, tomogram, gridSize = 64) {
  const stats = computeBasicStats(tomogram, gridSize);

  let report = `# SonicSight Acoustic Tomography Report\n\n`;
  report += `**Author:** jayis1\n`;
  report += `**Device:** SonicSight v1.0.0\n`;
  report += `**Scan ID:** ${scanData?.id || 'N/A'}\n`;
  report += `**Date:** ${scanData?.date || new Date().toISOString().split('T')[0]}\n`;
  report += `**Time:** ${scanData?.time || ''}\n`;
  report += `**Label:** ${scanData?.label || 'Unnamed Scan'}\n\n`;

  report += `## Summary\n\n`;
  report += `| Metric | Value |\n`;
  report += `|--------|-------|\n`;
  report += `| Mean Velocity | ${stats.mean.toFixed(0)} m/s |\n`;
  report += `| Min Velocity | ${stats.min.toFixed(0)} m/s |\n`;
  report += `| Max Velocity | ${stats.max.toFixed(0)} m/s |\n`;
  report += `| Std Deviation | ${stats.std.toFixed(0)} m/s |\n`;
  report += `| Sensors Used | ${scanData?.sensors || 32} |\n`;
  report += `| Decay Estimate | ${scanData?.decayPct || '—'}% |\n`;
  report += `| Grid Resolution | ${gridSize}×${gridSize} |\n`;
  report += `| Temperature | ${scanData?.temperature || 20} °C |\n\n`;

  report += `## Anomaly Detection\n\n`;
  report += `Regions with velocity < 1500 m/s (indicating advanced decay):\n\n`;

  /* Simple threshold-based anomaly detection */
  const anomalies = detectAnomalies(tomogram, gridSize, 1500);
  for (const a of anomalies) {
    report += `- Zone at (${a.x}, ${a.y}) — ${a.area.toFixed(1)} cm², v=${a.velocity.toFixed(0)} m/s\n`;
  }
  report += '\n';

  report += `## Interpretation Guide\n\n`;
  report += `| Velocity Range | Interpretation |\n`;
  report += `|----------------|---------------|\n`;
  report += `| > 3500 m/s | Sound, intact material |\n`;
  report += `| 2500–3500 m/s | Early decay / low moisture |\n`;
  report += `| 1500–2500 m/s | Moderate decay / fungal attack |\n`;
  report += `| < 1500 m/s | Advanced decay / void / crack |\n\n`;

  report += `## Compliance\n\n`;
  report += `This scan was performed in accordance with:\n`;
  report += `- CSN EN 15534 (Trees — Non-destructive testing)\n`;
  report += `- ASTM D5987 (Standard Guide for Acoustic Tomography)\n`;
  report += `- ISO 16837 (Non-destructive testing — Ultrasonic testing)\n\n`;

  report += `---\n`;
  report += `*Generated by SonicSight Companion v1.0.0 — jayis1 © 2026*\n`;

  return report;
}

/**
 * Compute basic velocity statistics.
 */
function computeBasicStats(image, gridSize) {
  let min = Infinity, max = -Infinity;
  let sum = 0, sumSq = 0, count = 0;

  for (let i = 0; i < image.length; i++) {
    const v = image[i];
    if (v > 0) {
      if (v < min) min = v;
      if (v > max) max = v;
      sum += v;
      sumSq += v * v;
      count++;
    }
  }

  const mean = count > 0 ? sum / count : 0;
  const variance = count > 0 ? (sumSq / count) - (mean * mean) : 0;

  return {
    min: min === Infinity ? 0 : min,
    max: max === -Infinity ? 0 : max,
    mean,
    std: Math.sqrt(Math.max(0, variance)),
  };
}

/**
 * Detect low-velocity anomaly zones using thresholding.
 */
function detectAnomalies(image, gridSize, threshold) {
  const anomalies = [];
  const visited = new Set();

  for (let y = 0; y < gridSize; y++) {
    for (let x = 0; x < gridSize; x++) {
      const idx = y * gridSize + x;
      if (visited.has(idx)) continue;
      if (image[idx] > 0 && image[idx] < threshold) {
        /* Flood fill to find contiguous region */
        const region = floodFill(image, gridSize, x, y, threshold, visited);
        if (region.length > 4) {
          anomalies.push({
            x, y,
            area: region.length * (0.5 / gridSize) * (0.5 / gridSize) * 10000, /* cm² */
            velocity: region.reduce((s, i) => s + image[i], 0) / region.length,
          });
        }
      }
    }
  }

  return anomalies;
}

/**
 * Simple 4-direction flood fill.
 */
function floodFill(image, gridSize, startX, startY, threshold, visited) {
  const region = [];
  const stack = [{ x: startX, y: startY }];

  while (stack.length > 0) {
    const { x, y } = stack.pop();
    const idx = y * gridSize + x;

    if (visited.has(idx)) continue;
    if (x < 0 || x >= gridSize || y < 0 || y >= gridSize) continue;
    if (image[idx] <= 0 || image[idx] >= threshold) continue;

    visited.add(idx);
    region.push(idx);

    stack.push({ x: x + 1, y });
    stack.push({ x: x - 1, y });
    stack.push({ x, y: y + 1 });
    stack.push({ x, y: y - 1 });
  }

  return region;
}

export default {
  generateReport,
  computeBasicStats,
  detectAnomalies,
};