/* HingeScribe local-first application controller. Author: jayis1. Copyright (c) 2026 jayis1. */
'use strict';
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const state={device:null,characteristic:null,events:JSON.parse(localStorage.getItem('hs-events')||'[]'),cycle:0};
function show(name){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===name));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));if(name==='history')renderHistory();}
function batteryPercent(mv){return Math.max(0,Math.min(100,Math.round((mv-2800)/14)));}
function renderStatus(s){$('#angle').textContent=`${s.angle.toFixed(1)}°`;$('#force').textContent=`${s.force.toFixed(1)} N`;$('#battery').textContent=`${batteryPercent(s.batteryMv)}%`;$('#harvest').textContent=`${s.harvestedMj} mJ`;$('#score').textContent=s.health;const alerts=HingeProtocol.flags(s.flags);$('#alerts').innerHTML=(alerts.length?alerts:['No maintenance issue detected in this cycle.']).map(x=>`<li>${escapeHtml(x)}</li>`).join('');}
function renderHistory(){const list=$('#events');if(!state.events.length){list.innerHTML='<p>No completed cycles stored yet.</p>';return;}list.innerHTML=state.events.slice().reverse().map(e=>`<article class="event ${e.health<75?'warn':''}"><b>Health ${e.health}/100</b><time>${new Date(e.timestamp).toLocaleString()}</time><p>${e.force.toFixed(1)} N peak opening force · ${e.harvestedMj} mJ recovered</p></article>`).join('');}
function escapeHtml(value){const node=document.createElement('span');node.textContent=String(value);return node.innerHTML;}
function storeEvent(event){state.events.push(event);if(state.events.length>128)state.events.shift();localStorage.setItem('hs-events',JSON.stringify(state.events));}
function simulate(){state.cycle++;const reading=HingeProtocol.synthetic(state.cycle);renderStatus(reading);storeEvent(reading);$('#connection').textContent='Simulator · latest cycle complete';}
async function connect(){if(!navigator.bluetooth){$('#connection').textContent='Web Bluetooth unavailable; simulator remains functional.';return;}try{state.device=await navigator.bluetooth.requestDevice({filters:[{namePrefix:'HingeScribe'}],optionalServices:['7c2e0001-8f4a-4a4b-a632-f3d8663c7f91']});const server=await state.device.gatt.connect();const service=await server.getPrimaryService('7c2e0001-8f4a-4a4b-a632-f3d8663c7f91');state.characteristic=await service.getCharacteristic('7c2e0002-8f4a-4a4b-a632-f3d8663c7f91');await state.characteristic.startNotifications();state.characteristic.addEventListener('characteristicvaluechanged',event=>{try{const bytes=new Uint8Array(event.target.value.buffer);const reading=HingeProtocol.decodeStatus(bytes);renderStatus(reading);storeEvent(reading);}catch(error){$('#connection').textContent=`Ignored malformed packet: ${error.message}`;}});state.device.addEventListener('gattserverdisconnected',()=>{$('#connection').textContent='Device disconnected; stored history remains available.';});$('#connection').textContent=`Connected to ${state.device.name}`;}catch(error){$('#connection').textContent=`Connection not completed: ${error.message}`;}}
function exportHistory(){const blob=new Blob([JSON.stringify({author:'jayis1',device:'HingeScribe',events:state.events},null,2)],{type:'application/json'});const anchor=document.createElement('a');anchor.href=URL.createObjectURL(blob);anchor.download='hingescribe-history.json';anchor.click();URL.revokeObjectURL(anchor.href);}
async function tare(){$('#calStatus').textContent='Taring… keep the door closed.';await new Promise(resolve=>setTimeout(resolve,800));localStorage.setItem('hs-calibrated',new Date().toISOString());$('#calStatus').textContent='Closed position saved locally. Hardware command will be sent when connected.';}
function saveSettings(){const settings={force:Number($('#forceLimit').value),close:Number($('#closeLimit').value),notifications:$('#notifications').checked};localStorage.setItem('hs-settings',JSON.stringify(settings));$('#connection').textContent='Thresholds saved locally.';}
$$('nav button').forEach(button=>button.addEventListener('click',()=>show(button.dataset.screen)));$('#connect').addEventListener('click',connect);$('#simulate').addEventListener('click',simulate);$('#export').addEventListener('click',exportHistory);$('#clear').addEventListener('click',()=>{if(confirm('Delete local HingeScribe history?')){state.events=[];localStorage.removeItem('hs-events');renderHistory();}});$('#tare').addEventListener('click',tare);$('#save').addEventListener('click',saveSettings);renderHistory();
