/* HingeScribe protocol codec. Author: jayis1. Copyright (c) 2026 jayis1. */
(function(root){'use strict';
const MAGIC=0x4853,VERSION=1;
function crc16(bytes){let crc=0xffff;for(const value of bytes){crc^=value<<8;for(let bit=0;bit<8;bit++)crc=(crc&0x8000)?((crc<<1)^0x1021)&0xffff:(crc<<1)&0xffff;}return crc;}
function view(bytes){return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);}
function validate(bytes){if(!(bytes instanceof Uint8Array)||bytes.length<8)throw new Error('Frame too short');const data=view(bytes);if(data.getUint16(0,true)!==MAGIC)throw new Error('Wrong device magic');if(bytes[2]!==VERSION)throw new Error('Unsupported protocol version');if(bytes[4]+8!==bytes.length)throw new Error('Length mismatch');if(bytes[bytes.length-1]!==10)throw new Error('Missing terminator');const expected=data.getUint16(bytes.length-3,true);const actual=crc16(bytes.slice(0,-3));if(expected!==actual)throw new Error('CRC mismatch');return true;}
function decodeStatus(bytes){validate(bytes);if(bytes[3]!==1||bytes[4]!==26)throw new Error('Not a status frame');const d=view(bytes);return{timestamp:d.getUint32(5,true),angle:d.getInt16(9,true)/100,velocity:d.getInt16(11,true)/10,force:d.getInt16(13,true)/100,temperature:d.getInt16(15,true)/100,batteryMv:d.getUint16(17,true),harvestedMj:d.getUint16(19,true),sequence:d.getUint32(21,true),health:d.getUint16(25,true),flags:d.getUint16(27,true),magnetValid:!!bytes[29],loadValid:!!bytes[30]};}
function flags(value){const names=[];if(value&1)names.push('Opening resistance is above baseline');if(value&2)names.push('Closed-angle drift suggests hinge sag');if(value&4)names.push('Closer is taking too long');if(value&8)names.push('Door is closing too quickly');if(value&16)names.push('Sensor needs inspection');if(value&32)names.push('Battery reserve is low');if(value&64)names.push('Possible obstruction detected');return names;}
function synthetic(cycle=1){return{timestamp:Date.now(),angle:0,velocity:0,force:18+cycle*1.8,temperature:21.5,batteryMv:3890,harvestedMj:64,sequence:cycle,health:Math.max(48,96-cycle*3),flags:cycle>5?1:0,magnetValid:true,loadValid:true};}
const api={crc16,validate,decodeStatus,flags,synthetic,MAGIC,VERSION};if(typeof module!=='undefined')module.exports=api;root.HingeProtocol=api;})(typeof window!=='undefined'?window:globalThis);
