// ============================================================
// LignoScan App — Report Screen
// Generates and displays PDF inspection reports
//
// Author: jayis1
// Copyright (C) 2026 jayis1. All rights reserved.
// License: MIT
// ============================================================

import React, { useState, useEffect } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet, ScrollView, AsyncStorage, Share, Alert,
} from 'react-native';
import { useBle } from '../utils/BleContext';
import { severityFromTDI, formatCoordinate, DECAY_LABELS } from '../utils/protocol';

export default function ReportScreen({ route, navigation }) {
  const { tomogram, gpsData } = useBle();
  const [scanData, setScanData] = useState(null);
  const [reportText, setReportText] = useState('');

  useEffect(() => {
    if (route.params?.scanId) {
      loadScan(route.params.scanId);
    } else if (tomogram) {
      // Use current active scan
      generateReport({
        treeId: 'TREE-CURRENT',
        timestamp: gpsData?.timestamp || new Date().toISOString(),
        tdi: tomogram.tdi,
        severity: severityFromTDI(tomogram.tdi),
        gps: { lat: gpsData?.latitude || 0, lon: gpsData?.longitude || 0 },
        tomogram,
      });
    }
  }, [route.params, tomogram, gpsData]);

  const loadScan = async (id) => {
    try {
      const stored = await AsyncStorage.getItem('lignoscan_scans');
      if (stored) {
        const scans = JSON.parse(stored);
        const scan = scans.find(s => s.id === id);
        if (scan) {
          setScanData(scan);
          generateReport(scan);
        }
      }
    } catch (e) {
      Alert.alert('Error', 'Could not load scan data.');
    }
  };

  const generateReport = (data) => {
    const severity = data.severity || severityFromTDI(data.tdi);
    const recommendation = getRecommendation(data.tdi);

    const report = `
══════════════════════════════════════════════
       LIGNOSCAN TREE INSPECTION REPORT
══════════════════════════════════════════════

Inspection Date: ${data.timestamp}
Tree ID: ${data.treeId}
Inspector: _________________

LOCATION:
  ${formatCoordinate(data.gps.lat, data.gps.lon)}
  Altitude: ${gpsData?.altitude?.toFixed(0) || 'N/A'} m

TOMOGRAPHIC ANALYSIS:
  Tomographic Decay Index (TDI): ${(data.tdi * 100).toFixed(1)}%
  Risk Assessment: ${severity.label}

DECAY CLASSIFICATION:
  • Sound Wood: Areas with normal stress-wave velocity
  • Moderate Decay: Early-stage decay detected
  • Severe Decay: Advanced structural degradation
  • Hollow: Near-air velocity (cavity likely)

RECOMMENDATION:
  ${recommendation}

──────────────────────────────────────────────
  This report was generated by LignoScan,
  a portable acoustic tomography scanner.

  Author: jayis1
  Copyright © 2026 jayis1
  License: MIT (software), CERN-OHL-S (hardware)
══════════════════════════════════════════════
`;
    setReportText(report);
  };

  const getRecommendation = (tdi) => {
    if (tdi < 0.1) {
      return 'Tree appears structurally sound. No action required. '
        + 'Recommend re-inspection in 12-24 months.';
    } else if (tdi < 0.25) {
      return 'Early-stage decay detected. Monitor tree health and '
        + 're-inspect in 6-12 months. Consider reducing canopy load '
        + 'if near high-risk targets.';
    } else if (tdi < 0.5) {
      return 'Significant decay detected. Recommend consultation with '
        + 'a certified arborist for detailed risk assessment. '
        + 'Consider pruning, cabling, or removal if near structures.';
    } else {
      return 'CRITICAL: Severe decay or hollow regions detected. '
        + 'Tree poses high failure risk. Immediate mitigation '
        + 'recommended — removal or significant reduction advised '
        + 'if near people or property.';
    }
  };

  const handleShare = async () => {
    try {
      await Share.share({
        message: reportText,
        title: `LignoScan Report — ${scanData?.treeId || 'Current Scan'}`,
      });
    } catch (e) {
      Alert.alert('Share Error', 'Could not share report.');
    }
  };

  return (
    <ScrollView style={styles.container}>
      <View style={styles.card}>
        <Text style={styles.title}>Inspection Report</Text>

        {reportText ? (
          <>
            <View style={styles.reportContainer}>
              <Text style={styles.reportText}>{reportText}</Text>
            </View>

            <View style={styles.actionRow}>
              <TouchableOpacity style={styles.shareButton} onPress={handleShare}>
                <Text style={styles.buttonText}>Share Report</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.inventoryButton}
                onPress={() => navigation.navigate('TreeInventory')}
              >
                <Text style={styles.buttonText}>View on Map</Text>
              </TouchableOpacity>
            </View>
          </>
        ) : (
          <View style={styles.empty}>
            <Text style={styles.emptyText}>No report data available</Text>
            <Text style={styles.emptySubtext}>
              Perform a scan first to generate an inspection report.
            </Text>
          </View>
        )}
      </View>

      <Text style={styles.footer}>
        Author: jayis1 — Copyright © 2026 — MIT License
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f0' },
  card: {
    backgroundColor: '#fff',
    margin: 12,
    padding: 16,
    borderRadius: 10,
    elevation: 2,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a3a1a',
    marginBottom: 12,
  },
  reportContainer: {
    backgroundColor: '#f9f9f0',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  reportText: {
    fontFamily: 'monospace',
    fontSize: 12,
    color: '#333',
    lineHeight: 18,
  },
  actionRow: { flexDirection: 'row', gap: 8 },
  shareButton: {
    backgroundColor: '#1a3a1a',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    alignItems: 'center',
  },
  inventoryButton: {
    backgroundColor: '#2d8a2d',
    padding: 12,
    borderRadius: 8,
    flex: 1,
    alignItems: 'center',
  },
  buttonText: { color: '#fff', fontSize: 14, fontWeight: 'bold' },
  empty: { alignItems: 'center', padding: 40 },
  emptyText: { fontSize: 18, color: '#999', marginBottom: 8 },
  emptySubtext: { fontSize: 14, color: '#aaa', textAlign: 'center' },
  footer: { textAlign: 'center', fontSize: 11, color: '#aaa', paddingVertical: 12 },
});

// EOF — ReportScreen.js
// Author: jayis1
// Copyright (C) 2026 jayis1. All rights reserved.
// License: MIT