/**
 * ForecastScreen.tsx — 5-day pollen risk forecast
 * Author: jayis1
 * Copyright (C) 2026 jayis1
 *
 * Forecast is generated by a cloud model that fuses the device's
 * per-minute counts with anemometer wind roses, meteorological data,
 * and seasonal taxon priors. The result is delivered via MQTT to the
 * app and displayed here as a color-coded 5-day strip.
 */
import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { Card } from '../components/Card';
import { useDevice } from '../components/DeviceContext';

const RISK_COLORS = {
  'low':       '#4CAF50',
  'moderate':  '#FFC107',
  'high':      '#FF6F00',
  'very-high': '#C62828',
};

export default function ForecastScreen() {
  const { forecast } = useDevice();

  if (!forecast.length) {
    return (
      <View style={styles.container}>
        <Text style={styles.empty}>No forecast yet. Forecast updates hourly once your AeroCast is online.</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <Text style={styles.title}>5-Day Pollen Forecast</Text>
      <Text style={styles.author}>AeroCast by jayis1</Text>
      <View style={styles.strip}>
        {forecast.map((d, i) => (
          <Card key={i} style={styles.dayCard}>
            <Text style={styles.date}>{d.date}</Text>
            <View style={[styles.badge, { backgroundColor: RISK_COLORS[d.risk] }]}>
              <Text style={styles.badgeText}>{d.risk.toUpperCase()}</Text>
            </View>
            <Text style={styles.taxon}>Top: {d.topTaxon}</Text>
            <Text style={styles.score}>Score {d.score.toFixed(1)}</Text>
          </Card>
        ))}
      </View>

      <Card>
        <Text style={styles.section}>How the forecast is computed</Text>
        <Text style={styles.body}>
          The cloud model combines your AeroCast's real-time classified counts
          with wind direction, temperature, humidity, and seasonal taxon priors.
          A gradient-boosted regression predicts next-day pollen/spore
          concentration for each taxon, then a risk threshold maps the score to
          low / moderate / high / very-high.
        </Text>
        <Text style={styles.body}>
          Author: jayis1 — model weights updated monthly from aggregate
          anonymized data across the AeroCast fleet.
        </Text>
      </Card>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0b1020' },
  title: { color: '#fff', fontSize: 22, fontWeight: '700', margin: 14 },
  author: { color: '#5CB4FF', fontSize: 12, marginLeft: 14, marginBottom: 8 },
  empty: { color: '#8aa', textAlign: 'center', marginTop: 80, paddingHorizontal: 30 },
  strip: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  dayCard: { flexBasis: '48%', flexGrow: 1 },
  date: { color: '#fff', fontSize: 14, fontWeight: '600' },
  badge: { borderRadius: 6, paddingVertical: 4, paddingHorizontal: 8, marginTop: 6, alignSelf: 'flex-start' },
  badgeText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  taxon: { color: '#cde', fontSize: 12, marginTop: 6 },
  score: { color: '#8aa', fontSize: 12 },
  section: { color: '#fff', fontSize: 15, fontWeight: '600', marginBottom: 6 },
  body: { color: '#abc', fontSize: 12, lineHeight: 18, marginBottom: 6 },
});