/*
 * model_weights.c - Quantized int8 model weights for Pollen Scout classifier
 *
 * In production these arrays are generated by STM32 X-CUBE-AI from a trained
 * MobileNetV2-0.35 model. Here we provide small placeholder weight tensors
 * with correct shapes and a deterministic pattern so the firmware compiles
 * and the forward pass is exercised end-to-end. Replace with real trained
 * weights before field deployment.
 *
 * Layer shapes:
 *   conv0: k=3, Cin=3,  Cout=16   -> 3*16*3*3 = 432 weights
 *   conv1: k=3, Cin=16, Cout=32   -> 16*32*3*3 = 4608 weights
 *   conv2: k=3, Cin=32, Cout=64   -> 32*64*3*3 = 18432 weights
 *   fc:    Cin=64,  Cout=40       -> 64*40     = 2560 weights
 *
 * Author: jayis1
 * Copyright (c) 2026 jayis1. All rights reserved.
 * SPDX-License-Identifier: GPL-3.0
 */
#include "model_weights.h"
#include <stdint.h>

/* Deterministic pseudo-random int8 generator for placeholder weights.
 * Replace these with real X-CUBE-AI generated constants. */
static int8_t make_w(int idx)
{
    int v = (idx * 17 + 5) % 251 - 125;   /* -125..125 */
    return (int8_t)v;
}

#define FILL(arr) \
    for (int i = 0; i < (int)(sizeof(arr)/sizeof(arr[0])); i++) arr[i] = make_w(i)

const int8_t  g_conv0_w[432]   = {0};   /* replaced at runtime by FILL */
const int8_t  g_conv1_w[4608]  = {0};
const int8_t  g_conv2_w[18432] = {0};
const int8_t  g_fc_w[2560]     = {0};

const int32_t g_conv0_b[16] = {0};
const int32_t g_conv1_b[32] = {0};
const int32_t g_conv2_b[64] = {0};
const int32_t g_fc_b[40]    = {0};

/* Pollen taxa & mold-spore class names (40 classes) */
const char *g_class_names[40] = {
    "Alnus (alder)",        "Ambrosia (ragweed)",   "Artemisia (mugwort)",
    "Betula (birch)",       "Carpinus (hornbeam)",  "Castanea (chestnut)",
    "Cedrus (cedar)",       "Corylus (hazel)",      "Cupressaceae (cypress)",
    "Fagus (beech)",        "Fraxinus (ash)",       "Juglans (walnut)",
    "Olea (olive)",         "Picea (spruce)",       "Pinus (pine)",
    "Plantago (plantain)",  "Platanus (plane)",     "Populus (poplar)",
    "Quercus (oak)",        "Rumex (sorrel)",       "Salix (willow)",
    "Tilia (linden)",       "Ulmus (elm)",          "Urtica (nettle)",
    "Acer (maple)",         "Aesculus (chestnut-tree)", "Carya (hickory)",
    "Sphagnum (moss)",      "Tsuga (hemlock)",      "Tilia cordata",
    "Poaceae (grass)",      "Lolium (ryegrass)",    "Phleum (timothy)",
    "Dactylis (orchardgrass)", "Festuca (fescue)",  "Poa (bluegrass)",
    "Cladosporium",         "Alternaria",           "Aspergillus",
    "Penicillium",          "Epicoccum",
};

/* Runtime weight initialization (called once by classifier_init if weights
 * are zero). In a production build this function is omitted and the
 * constants above are populated by the toolchain. */
void model_weights_ensure(void)
{
    static int done = 0;
    if (done) return;
    done = 1;
    FILL((int8_t *)g_conv0_w);
    FILL((int8_t *)g_conv1_w);
    FILL((int8_t *)g_conv2_w);
    FILL((int8_t *)g_fc_w);
}