/*
 * forest.c — int8 decision-forest inference engine.
 *
 * Author : jayis1
 * License: MIT
 *
 * Each tree is a complete binary tree stored as arrays of (feature_index,
 * threshold, leaf_label). We traverse from the root: at each internal node
 * we compare features[feat_idx] <= threshold; if true go left, else right.
 * Leaves store a class label. The forest votes by plurality.
 *
 * The actual weights are in forest_weights.c (generated by an offline
 * scikit-learn export script). This file is the engine only.
 */
#include "forest.h"
#include "forest_weights.h"
#include <string.h>

void clf_init(void) {
    /* Weights are const arrays in flash; nothing to do at runtime except
     * optionally verify the magic header. */
}

/* Traverse a single tree. Each node is 4 bytes: feat_idx (uint8), threshold
 * (int8 quantised), and two child offsets packed into a uint16. We use the
 * simpler CSR layout from forest_weights.h. */
static int tree_predict(const int8_node_t *nodes, int n_nodes,
                        const float *features) {
    int idx = 0;
    while (idx < n_nodes) {
        const int8_node_t *nd = &nodes[idx];
        if (nd->feat_idx == 0xFF) {
            return nd->leaf_label;     /* leaf */
        }
        /* Quantise the feature to int8 the same way training did:
         * features are roughly in [-128, 127] after standardisation; we
         * clip. */
        int32_t q = (int32_t)(features[nd->feat_idx] * 8.0f);
        if (q > 127)  q = 127;
        if (q < -128) q = -128;
        if (q <= nd->threshold) idx = 2*idx + 1;   /* left */
        else                    idx = 2*idx + 2;   /* right */
    }
    return 0;
}

int clf_classify(const float *features, clf_result_t *out) {
    int votes[CLF_N_CLASSES];
    memset(votes, 0, sizeof(votes));

    for (int t = 0; t < CLF_N_TREES; t++) {
        int label = tree_predict(forest_trees[t], forest_tree_sizes[t], features);
        if (label >= 0 && label < CLF_N_CLASSES) votes[label]++;
    }

    /* Plurality. */
    int best = 0, best_v = 0;
    for (int c = 0; c < CLF_N_CLASSES; c++) {
        if (votes[c] > best_v) { best_v = votes[c]; best = c; }
    }
    out->species_id  = best;
    out->score       = (float)best_v / CLF_N_TREES;
    out->confidence  = (int)(out->score * 100.0f);

    /* Class 0 is "ambient/no-insect"; treat as "no detection". */
    return (best != 0) ? 1 : 0;
}

/* ---- Species table ------------------------------------------------ */
static const char *g_names[CLF_N_CLASSES] = {
    "ambient",                 /* 0 */
    "Gryllus campestris",      /* 1 */
    "Acheta domesticus",       /* 2 */
    "Oecanthus spp.",          /* 3 */
    "Tibicen spp.",            /* 4 */
    "Magicicada spp.",         /* 5 */
    "Locusta migratoria",      /* 6 */
    "Schistocerca gregaria",   /* 7 */
    "Reticulitermes flavipes", /* 8 */
    "Coptotermes formosanus",  /* 9 */
    "Camponotus spp.",         /* 10 */
    "Hylotrupes bajulus",      /* 11 */
    "Anobium punctatum",       /* 12 */
    "Sitophilus granarius",    /* 13 */
    "Sitophilus oryzae",       /* 14 */
    "Tribolium castaneum",     /* 15 */
    "Plodia interpunctella",   /* 16 */
    "Cydia pomonella",         /* 17 */
    "Lygus spp.",              /* 18 */
    "Empoasca spp.",           /* 19 */
    "Nezara viridula",         /* 20 */
    "Halictus spp.",           /* 21 */
    "Achroia grisella",        /* 22 */
    "Tineola bisselliella",    /* 23 */
    "Lasius spp.",             /* 24 */
    "unknown",                 /* 25 */
};

const char *clf_species_name(int id) {
    if (id < 0 || id >= CLF_N_CLASSES) return "invalid";
    return g_names[id];
}