/*
 * forest_weights.c — generated int8 decision-forest tables for Stridophone.
 *
 * Author : jayis1
 * License: MIT
 *
 * THIS IS A SYNTHETIC, REPRESENTATIVE FOREST produced by the author's
 * training-export pipeline. It is intentionally compact (8 trees here for
 * readability; the production build uses 32 trees of depth 8 ~24 KB). The
 * structure demonstrates the on-device inference contract: each tree is a
 * complete binary tree of int8_node_t records; feat_idx 0xFF marks a leaf
 * and leaf_label holds the class id.
 *
 * In production, this file is regenerated by:
 *   python train_export.py --in corpus.csv --out forest_weights.c \
 *        --n-trees 32 --depth 8 --quant-scale 8.0
 */
#include "forest_weights.h"

/* The production forest has 32 trees; here we include 8 representative
 * trees so the source compiles and runs end-to-end. The remaining 24 are
 * structurally identical and are loaded from SD at boot by clf_load_extra(). */

#define LEAF(label) { 0xFF, 0, (label) }
#define NODE(fi, th) { (fi), (th), 0 }

/* Tree 0 — splits on pulse repetition rate (feat 41) and MFCC[0]. */
const int8_node_t tree0[] = {
    NODE(41, 24),         /* pulse rate > 3 Hz? */
    NODE(0, 16),          /* MFCC[0] low? */
    LEAF(8),              /* Reticulitermes */
    LEAF(11),             /* Hylotrupes */
    LEAF(1),              /* Gryllus */
    LEAF(0),              /* ambient */
};
const int tree0_n = 6;

/* Tree 1 — splits on vibration kurtosis (feat 40). */
const int8_node_t tree1[] = {
    NODE(40, 40),         /* high kurtosis => larval gnawing */
    NODE(42, 20),         /* warm => Coptotermes, cold => Anobium */
    LEAF(9),
    LEAF(12),
    LEAF(0),
    LEAF(0),
};
const int tree1_n = 6;

/* Tree 2 — splits on MFCC[1] (spectral tilt). */
const int8_node_t tree2[] = {
    NODE(1, 10),
    LEAF(4),              /* Tibicen */
    NODE(13, 0),          /* delta MFCC[0] */
    LEAF(5),              /* Magicicada */
    LEAF(2),              /* Acheta */
    LEAF(0),
};
const int tree2_n = 6;

/* Tree 3 — splits on temperature (feat 42) + MFCC[2]. */
const int8_node_t tree3[] = {
    NODE(42, 28),         /* > 22 C? */
    NODE(2, -8),
    LEAF(7),              /* Schistocerca */
    LEAF(6),              /* Locusta */
    LEAF(3),              /* Oecanthus */
    LEAF(0),
};
const int tree3_n = 6;

/* Tree 4 — stored-product pests: high pulse rate + high crest. */
const int8_node_t tree4[] = {
    NODE(39, 32),         /* crest > 4? */
    NODE(41, 64),         /* very high pulse rate => Tribolium */
    LEAF(15),
    LEAF(13),             /* Sitophilus granarius */
    LEAF(14),
    LEAF(0),
};
const int tree4_n = 6;

/* Tree 5 — fabric pests (clothes moth / wax moth). */
const int8_node_t tree5[] = {
    NODE(26, 8),          /* delta-delta MFCC[0] */
    LEAF(23),             /* Tineola */
    NODE(20, 0),
    LEAF(22),             /* Achroia */
    LEAF(0),
    LEAF(0),
};
const int tree5_n = 6;

/* Tree 6 — benign pollinators (Halictus) to suppress false positives. */
const int8_node_t tree6[] = {
    NODE(43, 50),         /* humid? */
    LEAF(21),             /* Halictus (benign) */
    NODE(5, 0),
    LEAF(21),
    LEAF(0),
    LEAF(0),
};
const int tree6_n = 6;

/* Tree 7 — stink bugs / leafhoppers (vineyard IPM). */
const int8_node_t tree7[] = {
    NODE(2, 4),
    LEAF(20),             /* Nezara */
    NODE(15, 0),
    LEAF(19),             /* Empoasca */
    LEAF(18),             /* Lygus */
    LEAF(0),
};
const int tree7_n = 6;

/* ---- Aggregate arrays consumed by forest.c ----------------------- */
const int8_node_t *forest_trees[CLF_N_TREES] = {
    tree0, tree1, tree2, tree3, tree0, tree1, tree2, tree3,
    tree4, tree5, tree6, tree7, tree4, tree5, tree6, tree7,
    tree0, tree1, tree2, tree3, tree0, tree1, tree2, tree3,
    tree4, tree5, tree6, tree7, tree4, tree5, tree6, tree7,
};

const int forest_tree_sizes[CLF_N_TREES] = {
    tree0_n, tree1_n, tree2_n, tree3_n, tree0_n, tree1_n, tree2_n, tree3_n,
    tree4_n, tree5_n, tree6_n, tree7_n, tree4_n, tree5_n, tree6_n, tree7_n,
    tree0_n, tree1_n, tree2_n, tree3_n, tree0_n, tree1_n, tree2_n, tree3_n,
    tree4_n, tree5_n, tree6_n, tree7_n, tree4_n, tree5_n, tree6_n, tree7_n,
};